apiVersion: v1
kind: Namespace
metadata:
  name: agents
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-servers
---
apiVersion: v1
kind: Namespace
metadata:
  name: litellm
---
apiVersion: v1
kind: Namespace
metadata:
  name: vllm
---
apiVersion: v1
kind: Namespace
metadata:
  name: ui
